const collection = [
    {
        name: 'Андрусь',
        surname: 'Bezdar',
        src: `../../assets/images/team/new/Andrus_Bezdar.jpg`,
        srcHidden: `../../assets/images/team/new/Andrus_Bezdar_color.jpg`,
        position: 'ceo & founder',
    },
    {
        name: 'Алексей',
        surname: 'Кораблев',
        src: `../../assets/images/team/new/Aleksey_Korablev.jpg`,
        srcHidden: `../../assets/images/team/new/Aleksey_Korablev_color.jpg`,
        position: 'ceo & founder',
    },
    {
        name: 'Роман',
        surname: 'Мохаммад',
        src: `../../assets/images/team/new/Roman_Mohammad.jpg`,
        srcHidden: `../../assets/images/team/new/Roman_Mohammad_color.jpg`,
        position: 'арт-директор',
    },
    {
        name: 'Елена',
        surname: 'Ажгирей',
        src: `../../assets/images/team/new/Elena_Azhgirey.jpg`,
        srcHidden: `../../assets/images/team/new/Elena_Azhgirey_color.jpg`,
        position: 'главный архитектор проекта',
    },
    {
        name: 'Андрей',
        surname: 'Лычковский',
        src: `../../assets/images/team/new/Andrey_Lychkovskiy.jpg`,
        srcHidden: `../../assets/images/team/new/Andrey_Lychkovskiy_color.jpg`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Александр',
        surname: 'Жаловский',
        src: `../../assets/images/team/new/Aleksandr_Zhalovskiy.jpg`,
        srcHidden: `../../assets/images/team/new/Aleksandr_Zhalovskiy_color.jpg`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Наталия',
        surname: 'Колясень',
        src: `../../assets/images/team/new/Natalia_Kolyasen.jpg`,
        srcHidden: `../../assets/images/team/new/Natalia_Kolyasen_color.jpg`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Наталья',
        surname: 'Ракша',
        src: `../../assets/images/team/new/Natalia_Raksha.jpg`,
        srcHidden: `../../assets/images/team/new/Natalia_Raksha_color.jpg`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Марк',
        surname: 'Гурда',
        src: `../../assets/images/team/new/Mark_Gurda.jpg`,
        srcHidden: `../../assets/images/team/new/Mark_Gurda_color.jpg`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Яна',
        surname: 'Багданович',
        src: `../../assets/images/team/new/Yana_Bagdanovich.jpg`,
        srcHidden: `../../assets/images/team/new/Yana_Bagdanovich_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Юлия',
        surname: 'Барылюк',
        src: `../../assets/images/team/new/Yulia_Barylyuk.jpg`,
        srcHidden: `../../assets/images/team/new/Yulia_Barylyuk_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Артём',
        surname: 'Ермолинский',
        src: `../../assets/images/team/new/Artem_Ermolinskiy.jpg`,
        srcHidden: `../../assets/images/team/new/Artem_Ermolinskiy_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Олег',
        surname: 'Повайбо',
        src: `../../assets/images/team/new/Oleg_Povaybo.jpg`,
        srcHidden: `../../assets/images/team/new/Oleg_Povaybo_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Елена',
        surname: 'Шипуля',
        src: `../../assets/images/team/new/Elena_Shipulya.jpg`,
        srcHidden: `../../assets/images/team/new/Elena_Shipulya_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Янина',
        surname: 'Новикова',
        src: `../../assets/images/team/new/Yanina_Novikova.jpg`,
        srcHidden: `../../assets/images/team/new/Yanina_Novikova_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Елена',
        surname: 'Ткаченко',
        src: `../../assets/images/team/new/Elena_Tkachenko.jpg`,
        srcHidden: `../../assets/images/team/new/Elena_Tkachenko_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Виктория',
        surname: 'Бекбаева',
        src: `../../assets/images/team/new/Viktoriya_Bekbaeva.jpg`,
        srcHidden: `../../assets/images/team/new/Viktoriya_Bekbaeva_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Валерия',
        surname: 'Павлова',
        src: `../../assets/images/team/new/Valeria_Pavlova.jpg`,
        srcHidden: `../../assets/images/team/new/Valeria_Pavlova_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Матвей',
        surname: 'Олейников',
        src: `../../assets/images/team/new/Matvey_Oleynikov.jpg`,
        srcHidden: `../../assets/images/team/new/Matvey_Oleynikov_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Аня',
        surname: 'Куцко',
        src: `../../assets/images/team/new/Anya_Kucko.jpg`,
        srcHidden: `../../assets/images/team/new/Anya_Kucko_color.jpg`,
        position: 'архитектор',
    },
    {
        name: 'Марьяна',
        src: `../../assets/images/team/new/Marianna.jpg`,
        srcHidden: `../../assets/images/team/new/Marianna_color.jpg`,
        position: 'архитектор-дизайнер',
    },
    {
        name: 'Алеся',
        surname: 'Трохимик',
        src: `../../assets/images/team/new/Alesya_Trohimik.jpg`,
        srcHidden: `../../assets/images/team/new/Alesya_Trohimik_color.jpg`,
        position: 'дизайнер',
    },
    {
        name: 'Анна',
        surname: 'Тимошук',
        src: `../../assets/images/team/new/Anna_Timoshuk.jpg`,
        srcHidden: `../../assets/images/team/new/Anna_Timoshuk_color.jpg`,
        position: 'дизайнер',
    },
    {
        name: 'Маруся',
        surname: 'Сивицкая',
        src: `../../assets/images/team/new/Marusya_Sivickaya.jpg`,
        srcHidden: `../../assets/images/team/new/Marusya_Sivickaya_color.jpg`,
        position: 'дизайнер мебели',
    },
    {
        name: 'Марина',
        surname: 'Гаврилина',
        src: `../../assets/images/team/new/Marina_Gavrilina.jpg`,
        srcHidden: `../../assets/images/team/new/Marina_Gavrilina_color.jpg`,
        position: 'маркетолог',
    },
    {
        name: 'Ирина',
        surname: 'Довыдчик',
        src: `../../assets/images/team/new/Irina_Dovydchik.jpg`,
        srcHidden: `../../assets/images/team/new/Irina_Dovydchik_color.jpg`,
        position: 'главный бухгалтер',
    },
];
