const collection = [
    {
        name: 'Андрусь',
        surname: 'Bezdar',
        src: `../../assets/images/team/Андрусь_Bezdar.png`,
        position: 'ceo & founder',
    },
    {
        name: 'Алексей',
        surname: 'Кораблев',
        src: `../../assets/images/team/Алексей_Кораблев.png`,
        position: 'ceo & founder',
    },
    {
        name: 'Роман',
        surname: 'Мохаммад',
        src: `../../assets/images/team/Роман_Мохаммад.png`,
        position: 'арт-директор',
    },
    {
        name: 'Елена',
        surname: 'Ажгирей',
        src: `../../assets/images/team/Elena_Azhgirey.png`,
        position: 'главный архитектор проекта',
    },
    {
        name: 'Андрей',
        surname: 'Лычковский',
        src: `../../assets/images/team/Andrey_Lychkovskiy.png`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Александр',
        surname: 'Жаловский',
        src: `../../assets/images/team/Aleksandr_Zhalovskiy.png`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Наталия',
        surname: 'Колясень',
        src: `../../assets/images/team/Наталия_Колясень.png`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Наталья',
        surname: 'Ракша',
        src: `../../assets/images/team/Наталья_Ракша.png`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Марк',
        surname: 'Гурда',
        src: `../../assets/images/team/Марк_Гурда.png`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Яна',
        surname: 'Багданович',
        src: `../../assets/images/team/Яна_Багданович.png`,
        position: 'архитектор',
    },
    {
        name: 'Юлия',
        surname: 'Барылюк',
        src: `../../assets/images/team/Юлия_Барылюк.png`,
        position: 'архитектор',
    },
    {
        name: 'Артём',
        surname: 'Ермолинский',
        src: `../../assets/images/team/Артём_Ермолинский.png`,
        position: 'архитектор',
    },
    {
        name: 'Олег',
        surname: 'Повайбо',
        src: `../../assets/images/team/Oleg_Povaybo.png`,
        position: 'архитектор',
    },
    {
        name: 'Елена',
        surname: 'Шипуля',
        src: `../../assets/images/team/Елена_Шипуля.png`,
        position: 'архитектор',
    },
    {
        name: 'Янина',
        surname: 'Новикова',
        src: `../../assets/images/team/Янина_Новикова.png`,
        position: 'архитектор',
    },
    {
        name: 'Елена',
        surname: 'Ткаченко',
        src: `../../assets/images/team/Елена_Ткаченко.png`,
        position: 'архитектор',
    },
    {
        name: 'Виктория',
        surname: 'Бекбаева',
        src: `../../assets/images/team/Виктория_Бекбаева.png`,
        position: 'архитектор',
    },
    {
        name: 'Валерия',
        surname: 'Павлова',
        src: `../../assets/images/team/Валерия_Павлова.png`,
        position: 'архитектор',
    },
    {
        name: 'Матвей',
        surname: 'Олейников',
        src: `../../assets/images/team/Matvey_Oleynikov.png`,
        position: 'архитектор',
    },
    {
        name: 'Аня',
        surname: 'Куцко',
        src: `../../assets/images/team/Аня_Куцко.png`,
        position: 'архитектор',
    },
    {
        name: 'Марьяна',
        src: `../../assets/images/team/Marianna.png`,
        position: 'архитектор-дизайнер',
    },
    {
        name: 'Алеся',
        surname: 'Трохимик',
        src: `../../assets/images/team/Алеся_Трохимик.png`,
        position: 'дизайнер',
    },
    {
        name: 'Анна',
        surname: 'Тимошук',
        src: `../../assets/images/team/Анна_Тимошук.png`,
        position: 'дизайнер',
    },
    {
        name: 'Маруся',
        surname: 'Сивицкая',
        src: `../../assets/images/team/Маруся_Сивицкая.png`,
        position: 'дизайнер мебели',
    },
    {
        name: 'Марина',
        surname: 'Гаврилина',
        src: `../../assets/images/team/Марина_Гаврилина.png`,
        position: 'маркетолог',
    },
    {
        name: 'Ирина',
        surname: 'Довыдчик',
        src: `../../assets/images/team/Ирина_Довыдчик.png`,
        position: 'главный бухгалтер',
    },
];