const collection = [
    {
        name: 'Андрусь',
        surname: 'Bezdar',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'ceo & founder',
    },
    {
        name: 'Алексей',
        surname: 'Кораблев',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'ceo & founder',
    },
    {
        name: 'Роман',
        surname: 'Мохаммад',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'арт-директор',
    },
    {
        name: 'Елена',
        surname: 'Ажгирей',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'главный архитектор проекта',
    },
    {
        name: 'Андрей',
        surname: 'Лычковский',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Александр',
        surname: 'Жаловский',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Наталия',
        surname: 'Колясень',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Наталья',
        surname: 'Ракша',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Марк',
        surname: 'Гурда',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор, team lead',
    },
    {
        name: 'Яна',
        surname: 'Багданович',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Юлия',
        surname: 'Барылюк',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Артём',
        surname: 'Ермолинский',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Олег',
        surname: 'Повайбо',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Елена',
        surname: 'Шипуля',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Янина',
        surname: 'Новикова',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Елена',
        surname: 'Ткаченко',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Виктория',
        surname: 'Бекбаева',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Валерия',
        surname: 'Павлова',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Матвей',
        surname: 'Олейников',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Аня',
        surname: 'Куцко',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'архитектор',
    },
    {
        name: 'Марьяна',
        src: `../../assets/images/team/${this.name}.png`,
        position: 'архитектор-дизайнер',
    },
    {
        name: 'Алеся',
        surname: 'Трохимик',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'дизайнер',
    },
    {
        name: 'Анна',
        surname: 'Тимошук',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'дизайнер',
    },
    {
        name: 'Маруся',
        surname: 'Сивицкая',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'дизайнер мебели',
    },
    {
        name: 'Марина',
        surname: 'Гаврилина',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'маркетолог',
    },
    {
        name: 'Ирина',
        surname: 'Довыдчик',
        src: `../../assets/images/team/${this.name}_${this.surname}.png`,
        position: 'главный бухгалтер',
    },
];