const collection = [
    {
        src: '../../assets/images/projects/cna_house.png',
        title: 'cna house',
        description: 'Дизайн дома',
        year: 2019,
        category: 'category-1',
    },
    {
        src: '../../assets/images/projects/matski_house.png',
        title: 'matski house',
        description: 'Проект дома',
        year: 2019,
        category: 'category-2',
    },
    {
        src: '../../assets/images/projects/ecspo_2020.png',
        title: 'экспо-2020',
        description: 'Проект павильона',
        year: 2018,
        category: 'category-3',
    },
    {
        src: '../../assets/images/projects/kindergarten.png',
        title: 'kindergarten',
        description: 'Разработка фасадов детского сада',
        year: 2018,
        category: 'category-1',
    },
    {
        src: '../../assets/images/projects/tomography.png',
        title: 'tomography',
        description: 'Реконструкция здания',
        year: 2018,
        category: 'category-2',
    },
    {
        src: '../../assets/images/projects/189_house.png',
        title: '189 house',
        description: 'Дизайн дома',
        year: 2018,
        category: 'category-3',
    },
    {
        src: '../../assets/images/projects/flying_house.png',
        title: 'flying house',
        description: 'Архитектурный проект дома',
        year: 2018,
        category: 'category-1',
    },
    {
        src: '../../assets/images/projects/literally_space.png',
        title: '#простокосмос',
        description: 'Проект жилого квартала',
        year: 2018,
        category: 'category-2',
    },
    {
        src: '../../assets/images/projects/zatsen.png',
        title: 'zatsen',
        description: 'Архитектурный проект дома',
        year: 2018,
        category: 'category-3',
    },
    {
        src: '../../assets/images/projects/wooden_house.png',
        title: 'wooden house',
        description: 'Архитектурный проект дома',
        year: 2018,
        category: 'category-1',
    },
    {
        src: '../../assets/images/projects/mark_house.png',
        title: 'mark house',
        description: 'Проект частного дома',
        year: 2018,
        category: 'category-2',
    },
    {
        src: '../../assets/images/projects/forrest.png',
        title: 'forrest',
        description: 'Проект жилого квартала',
        year: 2018,
        category: 'category-3',
    },
    {
        src: '../../assets/images/projects/galitsa.png',
        title: 'galitsa',
        description: 'Проект частного дома',
        year: 2018,
        category: 'category-1',
    },
    {
        src: '../../assets/images/projects/kordis_exterior.png',
        title: 'kordis exterior',
        description: 'Проект',
        year: 2018,
        category: 'category-2',
    },
];
